In [1]:
# By Miguel Maricalva and Philip Claesson

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

#train_final.csv - the training set of interactions
train_final = pd.read_csv('input/train_final.csv', delimiter = "\t");

#tracks_final.csv - supplementary information about the items
tracks_final = pd.read_csv('input/tracks_final.csv', delimiter = "\t");

#playlists_final.csv - supplementary information about the users
#playlists_final = pd.read_csv('input/playlists_final.csv');

#target_playlists.csv - the set of target playlists that will receive recommendations
target_playlists = pd.read_csv('input/target_playlists.csv');

#target_tracks.csv - the set of target items (tracks) to be recommended
target_tracks = pd.read_csv('input/target_tracks.csv');

#Let's have a look at the train data. 
train_final.head()

   playlist_id  track_id
0      3271849   2801526
1      5616275    727878
2     11267488   2805283
3     10103900   1515105
4      3836898   2945623

In [2]:
tracks_final.head()

,track_id,artist_id,duration,playcount,album,tags
0,2972914,144,224000,49.0,[7],"[54087, 1757, 1718, 116712, 189631]"
1,2750239,246,157000,1.0,[8],"[189631, 3424, 177424, 46208, 205245]"
2,1550729,144,217000,554.0,[9],"[54087, 109806, 46869, 183258, 54337]"
3,2169950,144,207000,200.0,[9],"[54087, 70618, 207003, 109806, 116712]"
4,1903709,144,198000,5.0,[None],"[54087, 81223, 116712, 215342, 71028]"

In [3]:
#Add occurence_count to the tracks_final dataset
tracks_final["occurence_count"] = 0

tracks_final.head()

,track_id,artist_id,duration,playcount,album,tags,occurence_count
0,2972914,144,224000,49.0,[7],"[54087, 1757, 1718, 116712, 189631]",0
1,2750239,246,157000,1.0,[8],"[189631, 3424, 177424, 46208, 205245]",0
2,1550729,144,217000,554.0,[9],"[54087, 109806, 46869, 183258, 54337]",0
3,2169950,144,207000,200.0,[9],"[54087, 70618, 207003, 109806, 116712]",0
4,1903709,144,198000,5.0,[None],"[54087, 81223, 116712, 215342, 71028]",0

In [5]:
#for each interaction, +1 at the song array

tracks_final[tracks_final['track_id'] == 2169950]


for track in train_final['track_id']:
    #tracks_final[tracks_final['track_id'] == track].occurence_count += 1
    
    tracks_final.loc[:,'track_id' == track, 'occurence_count'] +=1

tracks_final.head()

KeyError: 'the label [False] is not in the [columns]'